
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "terraria.serviceAccountName" . }}
  namespace: {{ include "terraria.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: realm-monitor
subjects:
- kind: ServiceAccount
  name: {{ include "terraria.serviceAccountName" . }}
  namespace: {{ include "terraria.namespace" . }}